[build]
  publish = "dist"
  command = "npm run build"

# SPA fallback for React Router (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Remove old hash-based redirects if any
[[redirects]]
  from = "/#/*"
  to = "/:splat"
  status = 301
  force = true

# Form success redirects
[[redirects]]
  from = "/contact-success"
  to = "/?success=contact"
  status = 302

[[redirects]]
  from = "/speaking-success"
  to = "/?success=speaking"
  status = 302

# Form settings
[build.environment]
  # Netlify will automatically detect forms with data-netlify="true"